# Based on ripgrep's release action:
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: Deploy Documentation
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.79.0
      - uses: Swatinem/rust-cache@v2
      # python3 and package jinja2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: python3 -m pip install jinja2 PyYAML
      - run: cargo test --package typst-docs --lib -- tests::test_docs --exact --nocapture
      - run: python3 ./gen.py
      # deploy ./dist to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: typst-doc-cn
          directory: "./dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Vercel
        env:
          VERCEL_JSON: ${{ secrets.VERCEL_JSON }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          mkdir -p .vercel
          echo $VERCEL_JSON > .vercel/project.json
          npx vercel --prod --yes --token $VERCEL_TOKEN
